# Generated by Django 4.0.4 on 2022-05-14 16:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('hospital', '0004_alter_department_options_alter_doctor_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='doctor',
            name='img',
            field=models.ImageField(upload_to='doctorimages/', verbose_name='医生照片'),
        ),
        migrations.CreateModel(
            name='TimeNumber',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('eight', models.IntegerField(verbose_name='八点可预约人数')),
                ('nine', models.IntegerField(verbose_name='九点可预约人数')),
                ('ten', models.IntegerField(verbose_name='十点可预约人数')),
                ('eleven', models.IntegerField(verbose_name='十一点可预约人数')),
                ('fourteen', models.IntegerField(verbose_name='十四点可预约人数')),
                ('fifteen', models.IntegerField(verbose_name='十五点可预约人数')),
                ('sixteen', models.IntegerField(verbose_name='十六点可预约人数')),
                ('seventeen', models.IntegerField(verbose_name='十七点可预约人数')),
                ('doctor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hospital.doctor')),
            ],
        ),
    ]
